---
- name: Allow Puppet Ports in Debian
  when: ansible_os_family == "Debian"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8139:8140
    jump: ACCEPT
    rule_num: 1
  tags: puppet-server
- name: Allow Puppet Ports in RedHat/CentOS
  when: ansible_os_family == "RedHat"
  firewalld:
    zone: public
    port: 8139-8140/tcp
    permanent: yes
    immediate: yes
    state: enabled
  tags: puppet-server